### ISSUE TITLE
WireFrame

### ISSUE THREAD

**Issue by BenRodwell** [BenRodwell/I-Have-No-Shelf-Control#1]

**Comment by hr-virieux** [comment]
Figma link - [https://www.figma.com/file/mwUoOD47AJ6mAjZ8wIAlQ6/Welcome-to-FigJam?type=whiteboard&node-id=0-1&t=Fr2Th5JpOSiB008e-0](url)

**Comment by hr-virieux** [comment]
Updates have been made to the previous sent link.

- Will need feedback on the layout of the reviews page. Want to do a layout that will be manageable within our time frame. 
- Account page is basic. Again don't want to put too much. So far you can see saved books/reviews and change avatar image.
- Home page, login/sign-up and contact seems to be done. Feel free to add comments.
